### PR TITLE
X3: Improve situation with move only types

### LINKED ISSUE #465: X3: container element copying bug
Another case of copying AST elements, I have 100+ line template backtrace for this (making minimal example would take some time) but I think that pointing to the code is enough:

`boost/spirit/home/x3/support/traits/container_traits.hpp`

```cpp
    template <typename Container, typename Enable = void>
    struct append_container
    {

    /* [...] */

        template <typename Iterator>
        static void insert(Container& c, Iterator first, Iterator last, mpl::false_)
        {
            c.insert(c.end(), first, last); // attemps to copy into c elements from range [first, last)
        }
    }
```

### PR DESCRIPTION
**Pull request by Kojoley**
Closes #465

### CODE REVIEW

**Comment by djowel** [comment]
Nice, as usual!

File: include/boost/spirit/home/x3/support/traits/container_traits.hpp [hunk 1]
```diff
@@ -122,15 +122,15 @@ namespace boost { namespace spirit { namespace x3 { namespace traits
...
+            c.insert(c.end(), static_cast<T&&>(val));
             return true;
         }
     };
 
     template <typename Container, typename T>
     inline bool push_back(Container& c, T&& val)
     {
-        return push_back_container<Container>::call(c, std::move(val));
+        return push_back_container<Container>::call(c, static_cast<T&&>(val));
```
Comment (Xeverous) [inline include/boost/spirit/home/x3/support/traits/container_traits.hpp]: What's the reason behind such changes? Reducing use of standard library (compile time)?

Comment (Kojoley) [reply include/boost/spirit/home/x3/support/traits/container_traits.hpp]: Removed surprising move of lvalue. And yes, `std::forward` is not zero cost in terms of compile time (also a surprising thing).
